//
// This file is autogenerated.
// To update, run:
//
//  make Jenkinsfile
//

pipeline {
  agent none
  environment {
    HOME = '/tmp/'
  }
  options {
    timestamps()
  }
  stages {
    stage('Prepare Build') {
      agent any
      steps {
        dir('official-images') {
          git url: 'https://github.com/docker-library/official-images'
        }
        stash includes: 'official-images/**', name: 'official-images'
      }
    }
    stage('Build Stage') {
      parallel {
        stage('2.7.16-stretch') {
          agent {
            label 'docker_builder_python'
          }
          environment {
            IMAGE_TAG = "2.7.16-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE = "python:$IMAGE_TAG"
          }
          stages {
            stage('2.7.16-stretch Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:2.7.16-stretch \
                  && docker tag \
                    $DOCKER_REGISTRY/python:2.7.16-stretch \
                    $IMAGE-cache \
                  && docker rmi $DOCKER_REGISTRY/python:2.7.16-stretch \
                  || true
                '''
              }
            }
            stage('2.7.16-stretch Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=2.7.16 \
                      --cache-from $IMAGE-cache \
                      --file 2.7/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('2.7.16-stretch Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('2.7.16-stretch Push') {
              steps {
                sh '''
                     docker tag $IMAGE $DOCKER_REGISTRY/python:2 \
                  && docker push $DOCKER_REGISTRY/python:2 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:2-stretch \
                  && docker push $DOCKER_REGISTRY/python:2-stretch \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:2.7 \
                  && docker push $DOCKER_REGISTRY/python:2.7 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:2.7-stretch \
                  && docker push $DOCKER_REGISTRY/python:2.7-stretch \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:2.7.16 \
                  && docker push $DOCKER_REGISTRY/python:2.7.16 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:2.7.16-stretch \
                  && docker push $DOCKER_REGISTRY/python:2.7.16-stretch
                '''
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE-cache \
                $DOCKER_REGISTRY/python:2 \
                $DOCKER_REGISTRY/python:2-stretch \
                $DOCKER_REGISTRY/python:2.7 \
                $DOCKER_REGISTRY/python:2.7-stretch \
                $DOCKER_REGISTRY/python:2.7.16 \
                $DOCKER_REGISTRY/python:2.7.16-stretch \
                --force
              '''
              sh 'make clean'
            }
          }
        }
        stage('3.5.3-stretch') {
          agent {
            label 'docker_builder_python'
          }
          environment {
            IMAGE_TAG = "3.5.3-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE = "python:$IMAGE_TAG"
          }
          stages {
            stage('3.5.3-stretch Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.5.3-stretch \
                  && docker tag \
                    $DOCKER_REGISTRY/python:3.5.3-stretch \
                    $IMAGE-cache \
                  && docker rmi $DOCKER_REGISTRY/python:3.5.3-stretch \
                  || true
                '''
              }
            }
            stage('3.5.3-stretch Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.5.3 \
                      --cache-from $IMAGE-cache \
                      --file 3.5/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.5.3-stretch Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.5.3-stretch Push') {
              steps {
                sh '''
                     docker tag $IMAGE $DOCKER_REGISTRY/python:3.5.3 \
                  && docker push $DOCKER_REGISTRY/python:3.5.3 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.5.3-stretch \
                  && docker push $DOCKER_REGISTRY/python:3.5.3-stretch
                '''
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE-cache \
                $DOCKER_REGISTRY/python:3.5.3 \
                $DOCKER_REGISTRY/python:3.5.3-stretch \
                --force
              '''
              sh 'make clean'
            }
          }
        }
        stage('3.5.4-stretch') {
          agent {
            label 'docker_builder_python'
          }
          environment {
            IMAGE_TAG = "3.5.4-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE = "python:$IMAGE_TAG"
          }
          stages {
            stage('3.5.4-stretch Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.5.4-stretch \
                  && docker tag \
                    $DOCKER_REGISTRY/python:3.5.4-stretch \
                    $IMAGE-cache \
                  && docker rmi $DOCKER_REGISTRY/python:3.5.4-stretch \
                  || true
                '''
              }
            }
            stage('3.5.4-stretch Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.5.4 \
                      --cache-from $IMAGE-cache \
                      --file 3.5/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.5.4-stretch Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.5.4-stretch Push') {
              steps {
                sh '''
                     docker tag $IMAGE $DOCKER_REGISTRY/python:3.5.4 \
                  && docker push $DOCKER_REGISTRY/python:3.5.4 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.5.4-stretch \
                  && docker push $DOCKER_REGISTRY/python:3.5.4-stretch
                '''
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE-cache \
                $DOCKER_REGISTRY/python:3.5.4 \
                $DOCKER_REGISTRY/python:3.5.4-stretch \
                --force
              '''
              sh 'make clean'
            }
          }
        }
        stage('3.5.5-stretch') {
          agent {
            label 'docker_builder_python'
          }
          environment {
            IMAGE_TAG = "3.5.5-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE = "python:$IMAGE_TAG"
          }
          stages {
            stage('3.5.5-stretch Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.5.5-stretch \
                  && docker tag \
                    $DOCKER_REGISTRY/python:3.5.5-stretch \
                    $IMAGE-cache \
                  && docker rmi $DOCKER_REGISTRY/python:3.5.5-stretch \
                  || true
                '''
              }
            }
            stage('3.5.5-stretch Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.5.5 \
                      --cache-from $IMAGE-cache \
                      --file 3.5/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.5.5-stretch Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.5.5-stretch Push') {
              steps {
                sh '''
                     docker tag $IMAGE $DOCKER_REGISTRY/python:3.5.5 \
                  && docker push $DOCKER_REGISTRY/python:3.5.5 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.5.5-stretch \
                  && docker push $DOCKER_REGISTRY/python:3.5.5-stretch
                '''
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE-cache \
                $DOCKER_REGISTRY/python:3.5.5 \
                $DOCKER_REGISTRY/python:3.5.5-stretch \
                --force
              '''
              sh 'make clean'
            }
          }
        }
        stage('3.5.6-stretch') {
          agent {
            label 'docker_builder_python'
          }
          environment {
            IMAGE_TAG = "3.5.6-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE = "python:$IMAGE_TAG"
          }
          stages {
            stage('3.5.6-stretch Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.5.6-stretch \
                  && docker tag \
                    $DOCKER_REGISTRY/python:3.5.6-stretch \
                    $IMAGE-cache \
                  && docker rmi $DOCKER_REGISTRY/python:3.5.6-stretch \
                  || true
                '''
              }
            }
            stage('3.5.6-stretch Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.5.6 \
                      --cache-from $IMAGE-cache \
                      --file 3.5/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.5.6-stretch Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.5.6-stretch Push') {
              steps {
                sh '''
                     docker tag $IMAGE $DOCKER_REGISTRY/python:3.5 \
                  && docker push $DOCKER_REGISTRY/python:3.5 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.5-stretch \
                  && docker push $DOCKER_REGISTRY/python:3.5-stretch \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.5.6 \
                  && docker push $DOCKER_REGISTRY/python:3.5.6 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.5.6-stretch \
                  && docker push $DOCKER_REGISTRY/python:3.5.6-stretch
                '''
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE-cache \
                $DOCKER_REGISTRY/python:3.5 \
                $DOCKER_REGISTRY/python:3.5-stretch \
                $DOCKER_REGISTRY/python:3.5.6 \
                $DOCKER_REGISTRY/python:3.5.6-stretch \
                --force
              '''
              sh 'make clean'
            }
          }
        }
        stage('3.6.0-stretch') {
          agent {
            label 'docker_builder_python'
          }
          environment {
            IMAGE_TAG = "3.6.0-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE = "python:$IMAGE_TAG"
          }
          stages {
            stage('3.6.0-stretch Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.6.0-stretch \
                  && docker tag \
                    $DOCKER_REGISTRY/python:3.6.0-stretch \
                    $IMAGE-cache \
                  && docker rmi $DOCKER_REGISTRY/python:3.6.0-stretch \
                  || true
                '''
              }
            }
            stage('3.6.0-stretch Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.6.0 \
                      --cache-from $IMAGE-cache \
                      --file 3.6/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.6.0-stretch Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.6.0-stretch Push') {
              steps {
                sh '''
                     docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.0 \
                  && docker push $DOCKER_REGISTRY/python:3.6.0 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.0-stretch \
                  && docker push $DOCKER_REGISTRY/python:3.6.0-stretch
                '''
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE-cache \
                $DOCKER_REGISTRY/python:3.6.0 \
                $DOCKER_REGISTRY/python:3.6.0-stretch \
                --force
              '''
              sh 'make clean'
            }
          }
        }
        stage('3.6.1-stretch') {
          agent {
            label 'docker_builder_python'
          }
          environment {
            IMAGE_TAG = "3.6.1-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE = "python:$IMAGE_TAG"
          }
          stages {
            stage('3.6.1-stretch Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.6.1-stretch \
                  && docker tag \
                    $DOCKER_REGISTRY/python:3.6.1-stretch \
                    $IMAGE-cache \
                  && docker rmi $DOCKER_REGISTRY/python:3.6.1-stretch \
                  || true
                '''
              }
            }
            stage('3.6.1-stretch Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.6.1 \
                      --cache-from $IMAGE-cache \
                      --file 3.6/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.6.1-stretch Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.6.1-stretch Push') {
              steps {
                sh '''
                     docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.1 \
                  && docker push $DOCKER_REGISTRY/python:3.6.1 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.1-stretch \
                  && docker push $DOCKER_REGISTRY/python:3.6.1-stretch
                '''
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE-cache \
                $DOCKER_REGISTRY/python:3.6.1 \
                $DOCKER_REGISTRY/python:3.6.1-stretch \
                --force
              '''
              sh 'make clean'
            }
          }
        }
        stage('3.6.2-stretch') {
          agent {
            label 'docker_builder_python'
          }
          environment {
            IMAGE_TAG = "3.6.2-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE = "python:$IMAGE_TAG"
          }
          stages {
            stage('3.6.2-stretch Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.6.2-stretch \
                  && docker tag \
                    $DOCKER_REGISTRY/python:3.6.2-stretch \
                    $IMAGE-cache \
                  && docker rmi $DOCKER_REGISTRY/python:3.6.2-stretch \
                  || true
                '''
              }
            }
            stage('3.6.2-stretch Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.6.2 \
                      --cache-from $IMAGE-cache \
                      --file 3.6/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.6.2-stretch Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.6.2-stretch Push') {
              steps {
                sh '''
                     docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.2 \
                  && docker push $DOCKER_REGISTRY/python:3.6.2 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.2-stretch \
                  && docker push $DOCKER_REGISTRY/python:3.6.2-stretch
                '''
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE-cache \
                $DOCKER_REGISTRY/python:3.6.2 \
                $DOCKER_REGISTRY/python:3.6.2-stretch \
                --force
              '''
              sh 'make clean'
            }
          }
        }
        stage('3.6.3-stretch') {
          agent {
            label 'docker_builder_python'
          }
          environment {
            IMAGE_TAG = "3.6.3-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE = "python:$IMAGE_TAG"
          }
          stages {
            stage('3.6.3-stretch Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.6.3-stretch \
                  && docker tag \
                    $DOCKER_REGISTRY/python:3.6.3-stretch \
                    $IMAGE-cache \
                  && docker rmi $DOCKER_REGISTRY/python:3.6.3-stretch \
                  || true
                '''
              }
            }
            stage('3.6.3-stretch Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.6.3 \
                      --cache-from $IMAGE-cache \
                      --file 3.6/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.6.3-stretch Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.6.3-stretch Push') {
              steps {
                sh '''
                     docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.3 \
                  && docker push $DOCKER_REGISTRY/python:3.6.3 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.3-stretch \
                  && docker push $DOCKER_REGISTRY/python:3.6.3-stretch
                '''
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE-cache \
                $DOCKER_REGISTRY/python:3.6.3 \
                $DOCKER_REGISTRY/python:3.6.3-stretch \
                --force
              '''
              sh 'make clean'
            }
          }
        }
        stage('3.6.4-stretch') {
          agent {
            label 'docker_builder_python'
          }
          environment {
            IMAGE_TAG = "3.6.4-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE = "python:$IMAGE_TAG"
          }
          stages {
            stage('3.6.4-stretch Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.6.4-stretch \
                  && docker tag \
                    $DOCKER_REGISTRY/python:3.6.4-stretch \
                    $IMAGE-cache \
                  && docker rmi $DOCKER_REGISTRY/python:3.6.4-stretch \
                  || true
                '''
              }
            }
            stage('3.6.4-stretch Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.6.4 \
                      --cache-from $IMAGE-cache \
                      --file 3.6/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.6.4-stretch Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.6.4-stretch Push') {
              steps {
                sh '''
                     docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.4 \
                  && docker push $DOCKER_REGISTRY/python:3.6.4 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.4-stretch \
                  && docker push $DOCKER_REGISTRY/python:3.6.4-stretch
                '''
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE-cache \
                $DOCKER_REGISTRY/python:3.6.4 \
                $DOCKER_REGISTRY/python:3.6.4-stretch \
                --force
              '''
              sh 'make clean'
            }
          }
        }
        stage('3.6.5-stretch') {
          agent {
            label 'docker_builder_python'
          }
          environment {
            IMAGE_TAG = "3.6.5-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE = "python:$IMAGE_TAG"
          }
          stages {
            stage('3.6.5-stretch Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.6.5-stretch \
                  && docker tag \
                    $DOCKER_REGISTRY/python:3.6.5-stretch \
                    $IMAGE-cache \
                  && docker rmi $DOCKER_REGISTRY/python:3.6.5-stretch \
                  || true
                '''
              }
            }
            stage('3.6.5-stretch Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.6.5 \
                      --cache-from $IMAGE-cache \
                      --file 3.6/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.6.5-stretch Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.6.5-stretch Push') {
              steps {
                sh '''
                     docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.5 \
                  && docker push $DOCKER_REGISTRY/python:3.6.5 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.5-stretch \
                  && docker push $DOCKER_REGISTRY/python:3.6.5-stretch
                '''
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE-cache \
                $DOCKER_REGISTRY/python:3.6.5 \
                $DOCKER_REGISTRY/python:3.6.5-stretch \
                --force
              '''
              sh 'make clean'
            }
          }
        }
        stage('3.6.6-stretch') {
          agent {
            label 'docker_builder_python'
          }
          environment {
            IMAGE_TAG = "3.6.6-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE = "python:$IMAGE_TAG"
          }
          stages {
            stage('3.6.6-stretch Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.6.6-stretch \
                  && docker tag \
                    $DOCKER_REGISTRY/python:3.6.6-stretch \
                    $IMAGE-cache \
                  && docker rmi $DOCKER_REGISTRY/python:3.6.6-stretch \
                  || true
                '''
              }
            }
            stage('3.6.6-stretch Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.6.6 \
                      --cache-from $IMAGE-cache \
                      --file 3.6/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.6.6-stretch Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.6.6-stretch Push') {
              steps {
                sh '''
                     docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.6 \
                  && docker push $DOCKER_REGISTRY/python:3.6.6 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.6-stretch \
                  && docker push $DOCKER_REGISTRY/python:3.6.6-stretch
                '''
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE-cache \
                $DOCKER_REGISTRY/python:3.6.6 \
                $DOCKER_REGISTRY/python:3.6.6-stretch \
                --force
              '''
              sh 'make clean'
            }
          }
        }
        stage('3.6.7-stretch') {
          agent {
            label 'docker_builder_python'
          }
          environment {
            IMAGE_TAG = "3.6.7-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE = "python:$IMAGE_TAG"
          }
          stages {
            stage('3.6.7-stretch Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.6.7-stretch \
                  && docker tag \
                    $DOCKER_REGISTRY/python:3.6.7-stretch \
                    $IMAGE-cache \
                  && docker rmi $DOCKER_REGISTRY/python:3.6.7-stretch \
                  || true
                '''
              }
            }
            stage('3.6.7-stretch Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.6.7 \
                      --cache-from $IMAGE-cache \
                      --file 3.6/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.6.7-stretch Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.6.7-stretch Push') {
              steps {
                sh '''
                     docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.7 \
                  && docker push $DOCKER_REGISTRY/python:3.6.7 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.7-stretch \
                  && docker push $DOCKER_REGISTRY/python:3.6.7-stretch
                '''
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE-cache \
                $DOCKER_REGISTRY/python:3.6.7 \
                $DOCKER_REGISTRY/python:3.6.7-stretch \
                --force
              '''
              sh 'make clean'
            }
          }
        }
        stage('3.6.8-stretch') {
          agent {
            label 'docker_builder_python'
          }
          environment {
            IMAGE_TAG = "3.6.8-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE = "python:$IMAGE_TAG"
          }
          stages {
            stage('3.6.8-stretch Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.6.8-stretch \
                  && docker tag \
                    $DOCKER_REGISTRY/python:3.6.8-stretch \
                    $IMAGE-cache \
                  && docker rmi $DOCKER_REGISTRY/python:3.6.8-stretch \
                  || true
                '''
              }
            }
            stage('3.6.8-stretch Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.6.8 \
                      --cache-from $IMAGE-cache \
                      --file 3.6/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.6.8-stretch Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.6.8-stretch Push') {
              steps {
                sh '''
                     docker tag $IMAGE $DOCKER_REGISTRY/python:3.6 \
                  && docker push $DOCKER_REGISTRY/python:3.6 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.6-stretch \
                  && docker push $DOCKER_REGISTRY/python:3.6-stretch \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.8 \
                  && docker push $DOCKER_REGISTRY/python:3.6.8 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.8-stretch \
                  && docker push $DOCKER_REGISTRY/python:3.6.8-stretch
                '''
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE-cache \
                $DOCKER_REGISTRY/python:3.6 \
                $DOCKER_REGISTRY/python:3.6-stretch \
                $DOCKER_REGISTRY/python:3.6.8 \
                $DOCKER_REGISTRY/python:3.6.8-stretch \
                --force
              '''
              sh 'make clean'
            }
          }
        }
        stage('3.7.0-stretch') {
          agent {
            label 'docker_builder_python'
          }
          environment {
            IMAGE_TAG = "3.7.0-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE = "python:$IMAGE_TAG"
          }
          stages {
            stage('3.7.0-stretch Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.7.0-stretch \
                  && docker tag \
                    $DOCKER_REGISTRY/python:3.7.0-stretch \
                    $IMAGE-cache \
                  && docker rmi $DOCKER_REGISTRY/python:3.7.0-stretch \
                  || true
                '''
              }
            }
            stage('3.7.0-stretch Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.7.0 \
                      --cache-from $IMAGE-cache \
                      --file 3.7/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.7.0-stretch Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.7.0-stretch Push') {
              steps {
                sh '''
                     docker tag $IMAGE $DOCKER_REGISTRY/python:3.7.0 \
                  && docker push $DOCKER_REGISTRY/python:3.7.0 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.7.0-stretch \
                  && docker push $DOCKER_REGISTRY/python:3.7.0-stretch
                '''
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE-cache \
                $DOCKER_REGISTRY/python:3.7.0 \
                $DOCKER_REGISTRY/python:3.7.0-stretch \
                --force
              '''
              sh 'make clean'
            }
          }
        }
        stage('3.7.1-stretch') {
          agent {
            label 'docker_builder_python'
          }
          environment {
            IMAGE_TAG = "3.7.1-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE = "python:$IMAGE_TAG"
          }
          stages {
            stage('3.7.1-stretch Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.7.1-stretch \
                  && docker tag \
                    $DOCKER_REGISTRY/python:3.7.1-stretch \
                    $IMAGE-cache \
                  && docker rmi $DOCKER_REGISTRY/python:3.7.1-stretch \
                  || true
                '''
              }
            }
            stage('3.7.1-stretch Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.7.1 \
                      --cache-from $IMAGE-cache \
                      --file 3.7/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.7.1-stretch Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.7.1-stretch Push') {
              steps {
                sh '''
                     docker tag $IMAGE $DOCKER_REGISTRY/python:3.7.1 \
                  && docker push $DOCKER_REGISTRY/python:3.7.1 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.7.1-stretch \
                  && docker push $DOCKER_REGISTRY/python:3.7.1-stretch
                '''
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE-cache \
                $DOCKER_REGISTRY/python:3.7.1 \
                $DOCKER_REGISTRY/python:3.7.1-stretch \
                --force
              '''
              sh 'make clean'
            }
          }
        }
        stage('3.7.2-stretch') {
          agent {
            label 'docker_builder_python'
          }
          environment {
            IMAGE_TAG = "3.7.2-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE = "python:$IMAGE_TAG"
          }
          stages {
            stage('3.7.2-stretch Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.7.2-stretch \
                  && docker tag \
                    $DOCKER_REGISTRY/python:3.7.2-stretch \
                    $IMAGE-cache \
                  && docker rmi $DOCKER_REGISTRY/python:3.7.2-stretch \
                  || true
                '''
              }
            }
            stage('3.7.2-stretch Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.7.2 \
                      --cache-from $IMAGE-cache \
                      --file 3.7/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.7.2-stretch Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.7.2-stretch Push') {
              steps {
                sh '''
                     docker tag $IMAGE $DOCKER_REGISTRY/python:3.7.2 \
                  && docker push $DOCKER_REGISTRY/python:3.7.2 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.7.2-stretch \
                  && docker push $DOCKER_REGISTRY/python:3.7.2-stretch
                '''
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE-cache \
                $DOCKER_REGISTRY/python:3.7.2 \
                $DOCKER_REGISTRY/python:3.7.2-stretch \
                --force
              '''
              sh 'make clean'
            }
          }
        }
        stage('3.7.3-stretch') {
          agent {
            label 'docker_builder_python'
          }
          environment {
            IMAGE_TAG = "3.7.3-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE = "python:$IMAGE_TAG"
          }
          stages {
            stage('3.7.3-stretch Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.7.3-stretch \
                  && docker tag \
                    $DOCKER_REGISTRY/python:3.7.3-stretch \
                    $IMAGE-cache \
                  && docker rmi $DOCKER_REGISTRY/python:3.7.3-stretch \
                  || true
                '''
              }
            }
            stage('3.7.3-stretch Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.7.3 \
                      --cache-from $IMAGE-cache \
                      --file 3.7/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.7.3-stretch Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.7.3-stretch Push') {
              steps {
                sh '''
                     docker tag $IMAGE $DOCKER_REGISTRY/python:3 \
                  && docker push $DOCKER_REGISTRY/python:3 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3-stretch \
                  && docker push $DOCKER_REGISTRY/python:3-stretch \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.7 \
                  && docker push $DOCKER_REGISTRY/python:3.7 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.7-stretch \
                  && docker push $DOCKER_REGISTRY/python:3.7-stretch \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.7.3 \
                  && docker push $DOCKER_REGISTRY/python:3.7.3 \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.7.3-stretch \
                  && docker push $DOCKER_REGISTRY/python:3.7.3-stretch \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:latest \
                  && docker push $DOCKER_REGISTRY/python:latest \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:stretch \
                  && docker push $DOCKER_REGISTRY/python:stretch
                '''
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE-cache \
                $DOCKER_REGISTRY/python:3 \
                $DOCKER_REGISTRY/python:3-stretch \
                $DOCKER_REGISTRY/python:3.7 \
                $DOCKER_REGISTRY/python:3.7-stretch \
                $DOCKER_REGISTRY/python:3.7.3 \
                $DOCKER_REGISTRY/python:3.7.3-stretch \
                $DOCKER_REGISTRY/python:latest \
                $DOCKER_REGISTRY/python:stretch \
                --force
              '''
              sh 'make clean'
            }
          }
        }
        stage('2.7.16-stretch-slim') {
          agent {
            label 'docker_builder_python'
          }
          environment {
            IMAGE_TAG = "2.7.16-stretch-slim-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE = "python:$IMAGE_TAG"
          }
          stages {
            stage('2.7.16-stretch-slim Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:2.7.16-stretch-slim \
                  && docker tag \
                    $DOCKER_REGISTRY/python:2.7.16-stretch-slim \
                    $IMAGE-cache \
                  && docker rmi $DOCKER_REGISTRY/python:2.7.16-stretch-slim \
                  || true
                '''
              }
            }
            stage('2.7.16-stretch-slim Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=2.7.16 \
                      --cache-from $IMAGE-cache \
                      --file 2.7/stretch/slim/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('2.7.16-stretch-slim Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('2.7.16-stretch-slim Push') {
              steps {
                sh '''
                     docker tag $IMAGE $DOCKER_REGISTRY/python:2-slim \
                  && docker push $DOCKER_REGISTRY/python:2-slim \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:2-stretch-slim \
                  && docker push $DOCKER_REGISTRY/python:2-stretch-slim \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:2.7-slim \
                  && docker push $DOCKER_REGISTRY/python:2.7-slim \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:2.7-stretch-slim \
                  && docker push $DOCKER_REGISTRY/python:2.7-stretch-slim \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:2.7.16-slim \
                  && docker push $DOCKER_REGISTRY/python:2.7.16-slim \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:2.7.16-stretch-slim \
                  && docker push $DOCKER_REGISTRY/python:2.7.16-stretch-slim
                '''
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE-cache \
                $DOCKER_REGISTRY/python:2-slim \
                $DOCKER_REGISTRY/python:2-stretch-slim \
                $DOCKER_REGISTRY/python:2.7-slim \
                $DOCKER_REGISTRY/python:2.7-stretch-slim \
                $DOCKER_REGISTRY/python:2.7.16-slim \
                $DOCKER_REGISTRY/python:2.7.16-stretch-slim \
                --force
              '''
              sh 'make clean'
            }
          }
        }
        stage('3.5.6-stretch-slim') {
          agent {
            label 'docker_builder_python'
          }
          environment {
            IMAGE_TAG = "3.5.6-stretch-slim-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE = "python:$IMAGE_TAG"
          }
          stages {
            stage('3.5.6-stretch-slim Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.5.6-stretch-slim \
                  && docker tag \
                    $DOCKER_REGISTRY/python:3.5.6-stretch-slim \
                    $IMAGE-cache \
                  && docker rmi $DOCKER_REGISTRY/python:3.5.6-stretch-slim \
                  || true
                '''
              }
            }
            stage('3.5.6-stretch-slim Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.5.6 \
                      --cache-from $IMAGE-cache \
                      --file 3.5/stretch/slim/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.5.6-stretch-slim Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.5.6-stretch-slim Push') {
              steps {
                sh '''
                     docker tag $IMAGE $DOCKER_REGISTRY/python:3.5-slim \
                  && docker push $DOCKER_REGISTRY/python:3.5-slim \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.5-stretch-slim \
                  && docker push $DOCKER_REGISTRY/python:3.5-stretch-slim \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.5.6-slim \
                  && docker push $DOCKER_REGISTRY/python:3.5.6-slim \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.5.6-stretch-slim \
                  && docker push $DOCKER_REGISTRY/python:3.5.6-stretch-slim
                '''
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE-cache \
                $DOCKER_REGISTRY/python:3.5-slim \
                $DOCKER_REGISTRY/python:3.5-stretch-slim \
                $DOCKER_REGISTRY/python:3.5.6-slim \
                $DOCKER_REGISTRY/python:3.5.6-stretch-slim \
                --force
              '''
              sh 'make clean'
            }
          }
        }
        stage('3.6.8-stretch-slim') {
          agent {
            label 'docker_builder_python'
          }
          environment {
            IMAGE_TAG = "3.6.8-stretch-slim-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE = "python:$IMAGE_TAG"
          }
          stages {
            stage('3.6.8-stretch-slim Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.6.8-stretch-slim \
                  && docker tag \
                    $DOCKER_REGISTRY/python:3.6.8-stretch-slim \
                    $IMAGE-cache \
                  && docker rmi $DOCKER_REGISTRY/python:3.6.8-stretch-slim \
                  || true
                '''
              }
            }
            stage('3.6.8-stretch-slim Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.6.8 \
                      --cache-from $IMAGE-cache \
                      --file 3.6/stretch/slim/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.6.8-stretch-slim Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.6.8-stretch-slim Push') {
              steps {
                sh '''
                     docker tag $IMAGE $DOCKER_REGISTRY/python:3.6-slim \
                  && docker push $DOCKER_REGISTRY/python:3.6-slim \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.6-stretch-slim \
                  && docker push $DOCKER_REGISTRY/python:3.6-stretch-slim \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.8-slim \
                  && docker push $DOCKER_REGISTRY/python:3.6.8-slim \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.8-stretch-slim \
                  && docker push $DOCKER_REGISTRY/python:3.6.8-stretch-slim
                '''
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE-cache \
                $DOCKER_REGISTRY/python:3.6-slim \
                $DOCKER_REGISTRY/python:3.6-stretch-slim \
                $DOCKER_REGISTRY/python:3.6.8-slim \
                $DOCKER_REGISTRY/python:3.6.8-stretch-slim \
                --force
              '''
              sh 'make clean'
            }
          }
        }
        stage('3.7.3-stretch-slim') {
          agent {
            label 'docker_builder_python'
          }
          environment {
            IMAGE_TAG = "3.7.3-stretch-slim-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE = "python:$IMAGE_TAG"
          }
          stages {
            stage('3.7.3-stretch-slim Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.7.3-stretch-slim \
                  && docker tag \
                    $DOCKER_REGISTRY/python:3.7.3-stretch-slim \
                    $IMAGE-cache \
                  && docker rmi $DOCKER_REGISTRY/python:3.7.3-stretch-slim \
                  || true
                '''
              }
            }
            stage('3.7.3-stretch-slim Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.7.3 \
                      --cache-from $IMAGE-cache \
                      --file 3.7/stretch/slim/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.7.3-stretch-slim Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.7.3-stretch-slim Push') {
              steps {
                sh '''
                     docker tag $IMAGE $DOCKER_REGISTRY/python:3-slim \
                  && docker push $DOCKER_REGISTRY/python:3-slim \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3-stretch-slim \
                  && docker push $DOCKER_REGISTRY/python:3-stretch-slim \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.7-slim \
                  && docker push $DOCKER_REGISTRY/python:3.7-slim \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.7-stretch-slim \
                  && docker push $DOCKER_REGISTRY/python:3.7-stretch-slim \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.7.3-slim \
                  && docker push $DOCKER_REGISTRY/python:3.7.3-slim \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:3.7.3-stretch-slim \
                  && docker push $DOCKER_REGISTRY/python:3.7.3-stretch-slim \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:slim \
                  && docker push $DOCKER_REGISTRY/python:slim \
                  && docker tag $IMAGE $DOCKER_REGISTRY/python:stretch-slim \
                  && docker push $DOCKER_REGISTRY/python:stretch-slim
                '''
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE-cache \
                $DOCKER_REGISTRY/python:3-slim \
                $DOCKER_REGISTRY/python:3-stretch-slim \
                $DOCKER_REGISTRY/python:3.7-slim \
                $DOCKER_REGISTRY/python:3.7-stretch-slim \
                $DOCKER_REGISTRY/python:3.7.3-slim \
                $DOCKER_REGISTRY/python:3.7.3-stretch-slim \
                $DOCKER_REGISTRY/python:slim \
                $DOCKER_REGISTRY/python:stretch-slim \
                --force
              '''
              sh 'make clean'
            }
          }
        }
      }
    }
  }
}
