//
// This file is autogenerated.
// To update, run:
//
//  make Jenkinsfile
//

pipeline {
  agent none
  environment {
    HOME = '/tmp/'
  }
  options {
    timestamps()
  }
  stages {
    stage('Prepare Build') {
      agent any
      steps {
        dir('official-images') {
          git url: 'https://github.com/docker-library/official-images'
        }
        stash includes: 'official-images/**', name: 'official-images'
      }
    }
    stage('Build Stage') {
      parallel {
        stage('2.7.16') {
          agent {
            label 'docker_builder'
          }
          environment {
            IMAGE = "python:2.7.16-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE_CACHE = "$IMAGE-cache"
          }
          stages {
            stage('2.7.16 Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:2.7.16 \
                  && docker tag $IMAGE_REPO:2.7.16 $IMAGE_CACHE \
                  || true
                '''
              }
            }
            stage('2.7.16 Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=2.7.16 \
                      --file 2.7/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('2.7.16 Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('2.7.16 Push') {
              steps {
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:2'
                sh 'docker push $DOCKER_REGISTRY/python:2'
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:2.7'
                sh 'docker push $DOCKER_REGISTRY/python:2.7'
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:2.7.16'
                sh 'docker push $DOCKER_REGISTRY/python:2.7.16'
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE_CACHE \
                $DOCKER_REGISTRY/python:2 \
                $DOCKER_REGISTRY/python:2.7 \
                $DOCKER_REGISTRY/python:2.7.16 \
                --force
              '''
              sh '''test -e official-images/test/clean.sh \
                && official-images/test/clean.sh \
                || true
              '''
            }
          }
        }
        stage('3.5.3') {
          agent {
            label 'docker_builder'
          }
          environment {
            IMAGE = "python:3.5.3-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE_CACHE = "$IMAGE-cache"
          }
          stages {
            stage('3.5.3 Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.5.3 \
                  && docker tag $IMAGE_REPO:3.5.3 $IMAGE_CACHE \
                  || true
                '''
              }
            }
            stage('3.5.3 Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.5.3 \
                      --file 3.5/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.5.3 Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.5.3 Push') {
              steps {
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:3.5.3'
                sh 'docker push $DOCKER_REGISTRY/python:3.5.3'
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE_CACHE \
                $DOCKER_REGISTRY/python:3.5.3 \
                --force
              '''
              sh '''test -e official-images/test/clean.sh \
                && official-images/test/clean.sh \
                || true
              '''
            }
          }
        }
        stage('3.5.4') {
          agent {
            label 'docker_builder'
          }
          environment {
            IMAGE = "python:3.5.4-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE_CACHE = "$IMAGE-cache"
          }
          stages {
            stage('3.5.4 Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.5.4 \
                  && docker tag $IMAGE_REPO:3.5.4 $IMAGE_CACHE \
                  || true
                '''
              }
            }
            stage('3.5.4 Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.5.4 \
                      --file 3.5/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.5.4 Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.5.4 Push') {
              steps {
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:3.5.4'
                sh 'docker push $DOCKER_REGISTRY/python:3.5.4'
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE_CACHE \
                $DOCKER_REGISTRY/python:3.5.4 \
                --force
              '''
              sh '''test -e official-images/test/clean.sh \
                && official-images/test/clean.sh \
                || true
              '''
            }
          }
        }
        stage('3.5.5') {
          agent {
            label 'docker_builder'
          }
          environment {
            IMAGE = "python:3.5.5-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE_CACHE = "$IMAGE-cache"
          }
          stages {
            stage('3.5.5 Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.5.5 \
                  && docker tag $IMAGE_REPO:3.5.5 $IMAGE_CACHE \
                  || true
                '''
              }
            }
            stage('3.5.5 Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.5.5 \
                      --file 3.5/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.5.5 Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.5.5 Push') {
              steps {
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:3.5.5'
                sh 'docker push $DOCKER_REGISTRY/python:3.5.5'
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE_CACHE \
                $DOCKER_REGISTRY/python:3.5.5 \
                --force
              '''
              sh '''test -e official-images/test/clean.sh \
                && official-images/test/clean.sh \
                || true
              '''
            }
          }
        }
        stage('3.5.6') {
          agent {
            label 'docker_builder'
          }
          environment {
            IMAGE = "python:3.5.6-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE_CACHE = "$IMAGE-cache"
          }
          stages {
            stage('3.5.6 Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.5.6 \
                  && docker tag $IMAGE_REPO:3.5.6 $IMAGE_CACHE \
                  || true
                '''
              }
            }
            stage('3.5.6 Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.5.6 \
                      --file 3.5/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.5.6 Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.5.6 Push') {
              steps {
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:3.5'
                sh 'docker push $DOCKER_REGISTRY/python:3.5'
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:3.5.6'
                sh 'docker push $DOCKER_REGISTRY/python:3.5.6'
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE_CACHE \
                $DOCKER_REGISTRY/python:3.5 \
                $DOCKER_REGISTRY/python:3.5.6 \
                --force
              '''
              sh '''test -e official-images/test/clean.sh \
                && official-images/test/clean.sh \
                || true
              '''
            }
          }
        }
        stage('3.6.0') {
          agent {
            label 'docker_builder'
          }
          environment {
            IMAGE = "python:3.6.0-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE_CACHE = "$IMAGE-cache"
          }
          stages {
            stage('3.6.0 Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.6.0 \
                  && docker tag $IMAGE_REPO:3.6.0 $IMAGE_CACHE \
                  || true
                '''
              }
            }
            stage('3.6.0 Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.6.0 \
                      --file 3.6/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.6.0 Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.6.0 Push') {
              steps {
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.0'
                sh 'docker push $DOCKER_REGISTRY/python:3.6.0'
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE_CACHE \
                $DOCKER_REGISTRY/python:3.6.0 \
                --force
              '''
              sh '''test -e official-images/test/clean.sh \
                && official-images/test/clean.sh \
                || true
              '''
            }
          }
        }
        stage('3.6.1') {
          agent {
            label 'docker_builder'
          }
          environment {
            IMAGE = "python:3.6.1-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE_CACHE = "$IMAGE-cache"
          }
          stages {
            stage('3.6.1 Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.6.1 \
                  && docker tag $IMAGE_REPO:3.6.1 $IMAGE_CACHE \
                  || true
                '''
              }
            }
            stage('3.6.1 Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.6.1 \
                      --file 3.6/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.6.1 Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.6.1 Push') {
              steps {
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.1'
                sh 'docker push $DOCKER_REGISTRY/python:3.6.1'
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE_CACHE \
                $DOCKER_REGISTRY/python:3.6.1 \
                --force
              '''
              sh '''test -e official-images/test/clean.sh \
                && official-images/test/clean.sh \
                || true
              '''
            }
          }
        }
        stage('3.6.2') {
          agent {
            label 'docker_builder'
          }
          environment {
            IMAGE = "python:3.6.2-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE_CACHE = "$IMAGE-cache"
          }
          stages {
            stage('3.6.2 Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.6.2 \
                  && docker tag $IMAGE_REPO:3.6.2 $IMAGE_CACHE \
                  || true
                '''
              }
            }
            stage('3.6.2 Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.6.2 \
                      --file 3.6/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.6.2 Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.6.2 Push') {
              steps {
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.2'
                sh 'docker push $DOCKER_REGISTRY/python:3.6.2'
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE_CACHE \
                $DOCKER_REGISTRY/python:3.6.2 \
                --force
              '''
              sh '''test -e official-images/test/clean.sh \
                && official-images/test/clean.sh \
                || true
              '''
            }
          }
        }
        stage('3.6.3') {
          agent {
            label 'docker_builder'
          }
          environment {
            IMAGE = "python:3.6.3-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE_CACHE = "$IMAGE-cache"
          }
          stages {
            stage('3.6.3 Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.6.3 \
                  && docker tag $IMAGE_REPO:3.6.3 $IMAGE_CACHE \
                  || true
                '''
              }
            }
            stage('3.6.3 Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.6.3 \
                      --file 3.6/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.6.3 Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.6.3 Push') {
              steps {
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.3'
                sh 'docker push $DOCKER_REGISTRY/python:3.6.3'
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE_CACHE \
                $DOCKER_REGISTRY/python:3.6.3 \
                --force
              '''
              sh '''test -e official-images/test/clean.sh \
                && official-images/test/clean.sh \
                || true
              '''
            }
          }
        }
        stage('3.6.4') {
          agent {
            label 'docker_builder'
          }
          environment {
            IMAGE = "python:3.6.4-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE_CACHE = "$IMAGE-cache"
          }
          stages {
            stage('3.6.4 Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.6.4 \
                  && docker tag $IMAGE_REPO:3.6.4 $IMAGE_CACHE \
                  || true
                '''
              }
            }
            stage('3.6.4 Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.6.4 \
                      --file 3.6/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.6.4 Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.6.4 Push') {
              steps {
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.4'
                sh 'docker push $DOCKER_REGISTRY/python:3.6.4'
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE_CACHE \
                $DOCKER_REGISTRY/python:3.6.4 \
                --force
              '''
              sh '''test -e official-images/test/clean.sh \
                && official-images/test/clean.sh \
                || true
              '''
            }
          }
        }
        stage('3.6.5') {
          agent {
            label 'docker_builder'
          }
          environment {
            IMAGE = "python:3.6.5-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE_CACHE = "$IMAGE-cache"
          }
          stages {
            stage('3.6.5 Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.6.5 \
                  && docker tag $IMAGE_REPO:3.6.5 $IMAGE_CACHE \
                  || true
                '''
              }
            }
            stage('3.6.5 Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.6.5 \
                      --file 3.6/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.6.5 Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.6.5 Push') {
              steps {
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.5'
                sh 'docker push $DOCKER_REGISTRY/python:3.6.5'
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE_CACHE \
                $DOCKER_REGISTRY/python:3.6.5 \
                --force
              '''
              sh '''test -e official-images/test/clean.sh \
                && official-images/test/clean.sh \
                || true
              '''
            }
          }
        }
        stage('3.6.6') {
          agent {
            label 'docker_builder'
          }
          environment {
            IMAGE = "python:3.6.6-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE_CACHE = "$IMAGE-cache"
          }
          stages {
            stage('3.6.6 Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.6.6 \
                  && docker tag $IMAGE_REPO:3.6.6 $IMAGE_CACHE \
                  || true
                '''
              }
            }
            stage('3.6.6 Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.6.6 \
                      --file 3.6/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.6.6 Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.6.6 Push') {
              steps {
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.6'
                sh 'docker push $DOCKER_REGISTRY/python:3.6.6'
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE_CACHE \
                $DOCKER_REGISTRY/python:3.6.6 \
                --force
              '''
              sh '''test -e official-images/test/clean.sh \
                && official-images/test/clean.sh \
                || true
              '''
            }
          }
        }
        stage('3.6.7') {
          agent {
            label 'docker_builder'
          }
          environment {
            IMAGE = "python:3.6.7-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE_CACHE = "$IMAGE-cache"
          }
          stages {
            stage('3.6.7 Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.6.7 \
                  && docker tag $IMAGE_REPO:3.6.7 $IMAGE_CACHE \
                  || true
                '''
              }
            }
            stage('3.6.7 Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.6.7 \
                      --file 3.6/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.6.7 Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.6.7 Push') {
              steps {
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.7'
                sh 'docker push $DOCKER_REGISTRY/python:3.6.7'
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE_CACHE \
                $DOCKER_REGISTRY/python:3.6.7 \
                --force
              '''
              sh '''test -e official-images/test/clean.sh \
                && official-images/test/clean.sh \
                || true
              '''
            }
          }
        }
        stage('3.6.8') {
          agent {
            label 'docker_builder'
          }
          environment {
            IMAGE = "python:3.6.8-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE_CACHE = "$IMAGE-cache"
          }
          stages {
            stage('3.6.8 Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.6.8 \
                  && docker tag $IMAGE_REPO:3.6.8 $IMAGE_CACHE \
                  || true
                '''
              }
            }
            stage('3.6.8 Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.6.8 \
                      --file 3.6/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.6.8 Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.6.8 Push') {
              steps {
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:3.6'
                sh 'docker push $DOCKER_REGISTRY/python:3.6'
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:3.6.8'
                sh 'docker push $DOCKER_REGISTRY/python:3.6.8'
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE_CACHE \
                $DOCKER_REGISTRY/python:3.6 \
                $DOCKER_REGISTRY/python:3.6.8 \
                --force
              '''
              sh '''test -e official-images/test/clean.sh \
                && official-images/test/clean.sh \
                || true
              '''
            }
          }
        }
        stage('3.7.0') {
          agent {
            label 'docker_builder'
          }
          environment {
            IMAGE = "python:3.7.0-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE_CACHE = "$IMAGE-cache"
          }
          stages {
            stage('3.7.0 Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.7.0 \
                  && docker tag $IMAGE_REPO:3.7.0 $IMAGE_CACHE \
                  || true
                '''
              }
            }
            stage('3.7.0 Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.7.0 \
                      --file 3.7/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.7.0 Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.7.0 Push') {
              steps {
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:3.7.0'
                sh 'docker push $DOCKER_REGISTRY/python:3.7.0'
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE_CACHE \
                $DOCKER_REGISTRY/python:3.7.0 \
                --force
              '''
              sh '''test -e official-images/test/clean.sh \
                && official-images/test/clean.sh \
                || true
              '''
            }
          }
        }
        stage('3.7.1') {
          agent {
            label 'docker_builder'
          }
          environment {
            IMAGE = "python:3.7.1-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE_CACHE = "$IMAGE-cache"
          }
          stages {
            stage('3.7.1 Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.7.1 \
                  && docker tag $IMAGE_REPO:3.7.1 $IMAGE_CACHE \
                  || true
                '''
              }
            }
            stage('3.7.1 Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.7.1 \
                      --file 3.7/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.7.1 Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.7.1 Push') {
              steps {
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:3.7.1'
                sh 'docker push $DOCKER_REGISTRY/python:3.7.1'
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE_CACHE \
                $DOCKER_REGISTRY/python:3.7.1 \
                --force
              '''
              sh '''test -e official-images/test/clean.sh \
                && official-images/test/clean.sh \
                || true
              '''
            }
          }
        }
        stage('3.7.2') {
          agent {
            label 'docker_builder'
          }
          environment {
            IMAGE = "python:3.7.2-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE_CACHE = "$IMAGE-cache"
          }
          stages {
            stage('3.7.2 Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.7.2 \
                  && docker tag $IMAGE_REPO:3.7.2 $IMAGE_CACHE \
                  || true
                '''
              }
            }
            stage('3.7.2 Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.7.2 \
                      --file 3.7/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.7.2 Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.7.2 Push') {
              steps {
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:3.7.2'
                sh 'docker push $DOCKER_REGISTRY/python:3.7.2'
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE_CACHE \
                $DOCKER_REGISTRY/python:3.7.2 \
                --force
              '''
              sh '''test -e official-images/test/clean.sh \
                && official-images/test/clean.sh \
                || true
              '''
            }
          }
        }
        stage('3.7.3') {
          agent {
            label 'docker_builder'
          }
          environment {
            IMAGE = "python:3.7.3-stretch-$BRANCH_NAME-$BUILD_NUMBER"
            IMAGE_CACHE = "$IMAGE-cache"
          }
          stages {
            stage('3.7.3 Pull Cache') {
              steps {
                sh '''docker pull $DOCKER_REGISTRY/python:3.7.3 \
                  && docker tag $IMAGE_REPO:3.7.3 $IMAGE_CACHE \
                  || true
                '''
              }
            }
            stage('3.7.3 Build') {
              steps {
                retry(10) {
                  sh '''docker build --tag $IMAGE \
                      --build-arg PYTHON_VERSION=3.7.3 \
                      --file 3.7/stretch/Dockerfile \
                      .
                  '''
                }
              }
            }
            stage('3.7.3 Test') {
              steps {
                unstash 'official-images'
                sh 'official-images/test/run.sh $IMAGE'
              }
            }
            stage('3.7.3 Push') {
              steps {
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:3'
                sh 'docker push $DOCKER_REGISTRY/python:3'
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:3.7'
                sh 'docker push $DOCKER_REGISTRY/python:3.7'
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:3.7.3'
                sh 'docker push $DOCKER_REGISTRY/python:3.7.3'
                sh 'docker tag $IMAGE $DOCKER_REGISTRY/python:latest'
                sh 'docker push $DOCKER_REGISTRY/python:latest'
              }
            }
          }
          post {
            cleanup {
              sh '''docker rmi \
                $IMAGE \
                $IMAGE_CACHE \
                $DOCKER_REGISTRY/python:3 \
                $DOCKER_REGISTRY/python:3.7 \
                $DOCKER_REGISTRY/python:3.7.3 \
                $DOCKER_REGISTRY/python:latest \
                --force
              '''
              sh '''test -e official-images/test/clean.sh \
                && official-images/test/clean.sh \
                || true
              '''
            }
          }
        }
      }
    }
  }
}
